# Generated by Django 4.2.2 on 2023-06-30 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TrainImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="train_images"),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("desc", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
