# Generated by Django 4.2.2 on 2023-06-30 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stockroom", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainimage",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="train"),
        ),
    ]
