# Generated by Django 4.2.2 on 2023-06-30 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stockroom", "0002_alter_trainimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainimage",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="train/"),
        ),
    ]
